### PR TITLE
Add support to inspect which keyword was violated.

### PR DESCRIPTION
**Pull request by rodrigosaito**
I have the necessity to check which keyword was violated, before showing the error in my API.

If you agree with this implementation I will complete this PR so you pull it into master.

### CODE REVIEW

**Comment by erosb** [comment]
I don't mind the purpose, and I also like the quality of implementation. I especially appreciate the way how you improve test readability with TestSupport.Failure.

Please go ahead with the implementation. I'm afraid I won't be able to do a detailed code review in the upcoming weeks though, so your PR won't be merged before the middle of June.

**Comment by erosb** [comment]
@rodrigosaito are you still working on it or can I review in its current state?

**Comment by rodrigosaito** [comment]
@erosb still missing a few keywords. I will try to finish this next weekend.

**Comment by erosb** [comment]
@rodrigosaito I merged this PR manually. It seemed to be a better idea, your branch was already conflicting in `ValidationException`, and I plan to make further improvements in that class, so it seemed to be a better idea to merge now. I will take over the remaining steps.

Thank you for working on this!

**Comment by rodrigosaito** [comment]
@erosb cool. sorry for not finishing this up. I didn't have the spare time to do so. Are you planning on releasing a new version of json-schema soon?

**Comment by erosb** [comment]
@rodrigosaito I'm sorry about the delay. Now version 1.4.0 is available on maven central.

**Comment by rodrigosaito** [comment]
great! thanks.

**Pull request merged**
