### PR TITLE
test case for issue #147

### PR DESCRIPTION
**Pull request by rkeytacked**
- regular expression that takes ages to validate using PCRE libs for pattern matching

### CODE REVIEW

**Comment by rkeytacked** [comment]
As expected the test case let's Travis CI run until timeout.

The quick idea to just replace `java.util.regex.Pattern` by `com.google.re2j.Pattern` fixes the exponential runtime, but raises a problem with the `equalsVerifier` tests.

**Comment by rkeytacked** [comment]
Just saw that https://github.com/google/re2j is BSD-3 licensed. Is this compatible with this project's Apache 2 License?

**Comment by rkeytacked** [comment]
ok, last commit fixes the `equalsVerifier` thingy, but now the code base is not backward compatible?

> Current codebase is not backward compatible (BACKWARD_COMPATIBLE_USER) with version <1.5.1>. Compatibility type has been detected as <NON_BACKWARD_COMPATIBLE>

**Comment by erosb** [comment]
Hello @rkeytacked , 

thank you for raising this PR.

The incompatibility with the previous versions is that `StringSchema#getPattern()` returned `java.util.regex.Pattern` before your change, but after the change it returns `com.google.re2j.Pattern`.

I will think about options to resolve this. It would be good to merge the PR, it is an important improvement.

**Comment by rkeytacked** [comment]
Hi @erosb , maybe it's possible to have a major version number change – like 1.6.0?

**Comment by erosb** [comment]
Hello @rkeytacked ,

1.6.0 is already released, actually 1.7.0 is also out and 1.8.0 is coming in a few days (newer versions are available on JitPack, not maven central).

Minor versions should be backwards-compatible, so only 2.0 would solve the problem, but I absolutely don't think it is time for the next major release.

I could resolve the backward-compatibility problem locally by converting from/to `java.util.regex.Pattern` in all public methods. I merge your PR then I'm going to resolve the build failure in the master branch.

**Pull request merged**
