### PR TITLE
Avro schema validation order preservation

### PR DESCRIPTION
**Pull request by sreekesh93**

### CODE REVIEW

**Review by erosb — CHANGES_REQUESTED** [review]
Hello,
thanks for raising the PR. Due to the severe performance tradeoff of `LinkedHashMap` over `HashMap` property ordering won't be acceptable for many users.

Therefore the use of `LinkedHashMap` can be only an optional thing, and this option should be turned off by default.

**Comment by sreekesh93** [comment]
> Hello, thanks for raising the PR. Due to the severe performance tradeoff of `LinkedHashMap` over `HashMap` property ordering won't be acceptable for many users.
> 
> Therefore the use of `LinkedHashMap` can be only an optional thing, and this option should be turned off by default.

Will raise PR with mentioned changes, Thanks @erosb

**Comment by erosb** [comment]
@sreekesh93 let me give you some ideas/clues on the implementation:

 * please create an additional flag in `SchemaLoaderBuilder` that let's the user configure if they want ordered object schemas or not
 *  this flag should be included in (and copied to, in the `SchemaLoader` constructor) `LoaderConfig` as well
 * let's create an `ObjectSchema` subclass, if possible, like `OrderedObjectSchema`  
 * let's extract all `HashMap` instantiations in `ObjectSchema` into separate package-private methods, and override these in `OrderedObjectSchema` so that they return `LinkedHashMap` instances
 * then the `ObjectSchemaExtractor` would instantiate either an `ObjectSchema` or an `OrderedObjectSchema` depending on the state of the config flag in `LoaderConfig`.

Briefly that would be it.

**Comment by erosb** [comment]
no response - closing the PR.

**Pull request closed without merging**
