### PR TITLE
Full-date format & full 'format' test cases

### PR DESCRIPTION
**Pull request by SwamWithTurtles**
As per issue number #52

### CODE REVIEW

**Comment by erosb** [comment]
@SwamWithTurtles thank you for getting back to this issue and working on it!

Two major things to do before going ahead:
 * please resolve the conflicts
 * I would more prefer implementing the tests as unittests (the simlest way is to add new testcases to `DefaultFormatValidatorTest`) instead of integration tests. `format.json` copied from the [official test suite](https://github.com/json-schema-org/JSON-Schema-Test-Suite) so it isn't supposed to be modified.

I will go through the code changes again later.

Thanks.

**Comment by xalexslx** [comment]
+1. Any ETA for merging and releasing a version with this feature?

**Comment by erosb** [comment]
This won't be merged as long as it conflicts with the existing codebase.

**Comment by erosb** [comment]
Closing this PR due to lack of activity.

**Comment by mindbender1** [comment]
If i need the functionality for "date" only - without any time - then i need to fix SwamWithTurtles try or reimplement this, right?

**Comment by erosb** [comment]
Hello @mindbender1 , the "date" format became a part of the JSON Schema spec in the latest version (draft-07). A new release is likely to arrive in a few days with draft-07 support, so if you can wait a few days, then I suggest doing so.

But if it is more urgent than that, then you can copy-paste from the draft-07 branch these classes:

 * [DateFormatValidator](https://github.com/everit-org/json-schema/blob/draft-07/core/src/main/java/org/everit/json/schema/internal/DateFormatValidator.java)
 * its superclass [TemporalFormatValidator](https://github.com/everit-org/json-schema/blob/draft-07/core/src/main/java/org/everit/json/schema/internal/TemporalFormatValidator.java)

**Comment by mindbender1** [comment]
thank you for your answer, this sounds great.
i will wait for this - i will test draft-07-support then.

**Pull request closed without merging**
