### PR TITLE
Updating Maven information based on jitpack.io

### PR DESCRIPTION
**Pull request by smarkwell**
Based on this https://jitpack.io/#everit-org/json-schema/1.6.0 I've updated the Maven link to reflect what appears to be the correct

### CODE REVIEW

**Comment by erosb** [comment]
Hi! I might overlook something, but the current groupId/artifactId seems to be correct for me, according to the link you referenced:

screenshot from 2017-10-10 07-08-19

**Comment by smarkwell** [comment]
Interesting, when I use the following URL I get my result
'https://github.com/everit-org/json-schema'

image

**Comment by smarkwell** [comment]
Another screen shot

image

**Comment by erosb** [comment]
That is strange.

Anyway, when I try to build a skeleton project with `com.github.everit-org:json-schema` then it fails to build.

**Pull request closed without merging**
