### PR TITLE
feat: migrate unit tests to JUnit 5 #349

### PR DESCRIPTION
**Pull request by gstoupis**
Migrated the "tests" project only to JUnit 5.7.0.

References #349

### CODE REVIEW

**Review by erosb — COMMENTED** [review]
Nice job! Do you also plan to migrate the unittests in the core submodule?

**Comment by gstoupis** [comment]
Thanks!  Yes, since you’re OK with what you see so far, I’ll continue with
the core submodule.

**Comment by erosb** [comment]
Hello, thanks for the update. I can see a couple of issues:
 - please remove the `pl.pragmatists:JUnitParams` dependency
 - the code coverage dropped on coveralls. That is most probably a mismeasurement, so first I suggest upgrading the related maven plugins in `core/pom.xml`: `jacoco-maven-plugin` to `0.8.6` and `maven-surefire-plugin` to `2.22.2`. If it doesn't help we can investigate deeper.
 - when running `grep 'import org.junit' core/src/test/**/*.java | grep -v jupiter` on your branch it currently yields 100 results, so I assume the migration is still WIP

**Comment by gstoupis** [comment]
> 
> 
> Hello, thanks for the update. I can see a couple of issues:
> 
>     * please remove the `pl.pragmatists:JUnitParams` dependency
> 
>     * the code coverage dropped on coveralls. That is most probably a mismeasurement, so first I suggest upgrading the related maven plugins in `core/pom.xml`: `jacoco-maven-plugin` to `0.8.6` and `maven-surefire-plugin` to `2.22.2`. If it doesn't help we can investigate deeper.
> 
>     * when running `grep 'import org.junit' core/src/test/**/*.java | grep -v jupiter` on your branch it currently yields 100 results, so I assume the migration is still WIP

Hi there @erosb,
The PR is still WIP, you're right. I accidentally pushed my personal branch. I'll let you know when I'm done migrating everything.

Thanks for the pointers!

**Comment by gstoupis** [comment]
Hi again @erosb ,

I believe I've completed everything there was to do around the migration. 

Awaiting for your review. Thanks!

**Review by erosb — APPROVED** [review]
Good job, I have a couple of minor stylistic changes in mind, but those can be addressed follow-up. Thank you for your contribution!

**Comment by gstoupis** [comment]
@erosb you're welcome! I'm interested in your view, so if you end up creating an issue for the stylistic changes, do mention me or the original issue so that I get notified. Thanks!

**Comment by erosb** [comment]
I just want to change the `assertThrows()` calls so that single-statement lambdas aren't wrapped into a block with braces, that's all :)

**Comment by gstoupis** [comment]
Oh yeah, you're right... Welp, that's a chance for some combing in the near future then. Thanks again!

**Pull request merged**
